ilk/Models/Admin.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ilk.Models
{
	public class Admin
	{
        [Key]
        public int AdminID { get; set; }


        [Column(TypeName = "Varchar(20)")]
        public int Kullanici { get; set; }


		[Column(TypeName = "Varchar(10)")]
		public int Sifre { get; set; }
    }
}

ilk/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ilk.Models
{
    public class Context:DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=DESKTOP-AKNTGAT; database=corePersonel; integrated security=true;");
        }
        public DbSet<Departman> Departmans { get; set; }
        public DbSet<Personel> Personels { get; set; }
		public DbSet<Admin> Admins { get; set; }
	}
}

ilk/Models/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ilk.Models
{
    public class Departman
    {
        [Key]
        public int departman_id { get; set; }
        public string departman_adi { get; set; }
        public List<Personel> Personels { get; set; }
    }
}
 

ilk/Models/ErrorViewModel.cs
using System;

namespace ilk.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ilk/Models/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ilk.Models
{
    public class Personel
    {
        [Key]

        public int personel_id { get; set; }
        public string personel_adi { get; set; }
        public string personel_soyadi { get; set; }
        public string personel_sehir { get; set; }
        public Departman Departman { get; set; }
    }
}

ilk/Models/departmanlar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ilk.Models
{
    public class departmanlar
    {
        [Key]
        public int departman_id { get; set; }
        public string departman_adi { get; set; }
    }
}

ilk/Models/personeller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ilk.Models
{
    public class personeller
    {
        [Key]

        public int personel_id { get; set; }
        public string personel_adi { get; set; }
        public string personel_soyadi { get; set; }
        public string personel_sehir { get; set; }


    }
}

ilk/Controllers/HomeController.cs
using ilk.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ilk.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ilk/Controllers/LoginController.cs
using ilk.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ilk.Controllers
{
	public class LoginController : Controller
	{
		Context c = new Context();
		[HttpGet]
		public IActionResult GirisYap()
		{
			return View();
		}

		public async Task<IActionResult> GirisYap(Admin p)  //async eklendi. identity kullanılacağı için asyns eklendi. önünde de Task<> komutu yazıldı.
		{
			var bilgiler = c.Admins.FirstOrDefault(x => x.Kullanici == p.Kullanici && x.Sifre == p.Sifre);
			if (bilgiler != null)
			{
				var claims = new List<Claim> 
				{
					new Claim(ClaimTypes.Name, p.Kullanici) 
				};

				var userIdentity = new ClaimsIdentity(claims, "Login");
				ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
				await HttpContext.SignInAsync(principal);
				return RedirectToAction("Index", "personel");
			}
			return View();
		}
	}
}

ilk/Controllers/departmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ilk.Models;
using System.Runtime.CompilerServices;

namespace ilk.Controllers
{
    public class departmanController : Controller
    {
        Context c = new Context();

        public IActionResult Index()
        {
            var degerler = c.Departmans;
            return View(degerler);
        }

        [HttpGet]
        public IActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult DepartmanEkle(Departman d)
        {
            c.Departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult DepartmanSil(int id)
        {
            var deger = c.Departmans.Find(id);
            c.Departmans.Remove(deger);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DepartmanGetir(int id)
        {
            var deger = c.Departmans.Find(id);
            return View("DepartmanGetir", deger);
        }

        public IActionResult DepartmanGuncelle(Departman d)
        {
            var dprtmn = c.Departmans.Find(d.departman_id);
            dprtmn.departman_adi = d.departman_adi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Where(x=>x.Departman.departman_id==id).ToList();
            var departAd = c.Departmans.Where(x => x.departman_id==id).Select(y=>y.departman_adi).FirstOrDefault();
            ViewBag.DepartmanAd = departAd;
            return View(degerler);
        }
    }
}

ilk/Controllers/personelController.cs
using ilk.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace ilk.Controllers
{
    public class personelController : Controller
    {
        Context c = new Context();
        [Authorize]
        public IActionResult Index()
        {
            var degerler = c.Personels.Include(x=>x.Departman).ToList();
            return View(degerler);
        }

        [HttpGet]
        public IActionResult YeniPersonel()
        {
            List<SelectListItem> degerler = (from x in c.Departmans.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.departman_adi, Value = x.departman_id.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();  
        }

        [HttpPost]
        public IActionResult YeniPersonel(Personel p)
        {
            var per = c.Departmans.Where(x=>x.departman_id==p.Departman.departman_id).FirstOrDefault();
            p.Departman = per;
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ilk/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ilk/Views/Login/GirisYap.cshtml
@{
    Layout = null;
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Blend Login Form Flat Responsive Widget Template :: w3layouts</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Blend  Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/web/css/font-awesome.css" rel="stylesheet"> <!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Vollkorn+SC:400,600,700,900&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Acme" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main">
		<h1>MVC Core 5.0 Giriş Formu</h1>
		<div class="main-w3lsrow">
			<!-- login form -->
			<div class="login-form login-form-left">
				<div class="agile-row">
					<h2>Giriş Paneli</h2>
					<div class="login-agileits-top">
						<form action="#" method="post">
							<p>Kullanıcı Adı</p>
							<input type="text" class="name" name="Kullanici" required="" />
							<p>Şifre</p>
							<input type="password" class="password" name="Sifre" required="" />
							<label class="anim">
								<input type="checkbox" class="checkbox">
								<span> Beni Hatırla</span>
							</label>
							<input type="submit" value="Giriş Yap">
						</form>
					</div>
					<div class="login-agileits-bottom">
						<h6><a href="#">Şifremi Unuttum</a></h6>
					</div>
					<div class="login-agileits-bottom1">
						<h3>veya</h3>

					</div>
					<div class="social_icons agileinfo">
						<ul class="top-links">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
						</ul>
					</div>

				</div>
			</div>
		</div>
		<!-- copyright -->
		<div class="copyright">
			<p> © 2023 Blend  Login Form. Tüm Hakları Saklıdır.</p>
		</div>
		<!-- //copyright -->
	</div>
	<!-- //main -->
</body>
</html>

ilk/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ilk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ilk</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ilk - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ilk/Views/Shared/_TestLayout.cshtml
@{
    Layout = null;
}

<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
        <h3 class="w3-bar-item">Menu</h3>
        <a href="/departman/Index" class="w3-bar-item w3-button">Departmanlar</a>
        <a href="/personel/Index" class="w3-bar-item w3-button">Personeller</a>
        <a href="#" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="#" class="w3-bar-item w3-button">Çıkış</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:25%">

        <div class="w3-container w3-teal">
            <h1>Asp.Net Core Mvc Proje Geliştirme</h1>
        </div>

        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>

ilk/Views/departman/DepartmanDetay.cshtml
@using ilk.Models
@model List<Personel>
@{
    ViewData["Title"] = "DepartmanDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<h2>
    @ViewBag.DepartmanAd Departmanı
</h2>
<br />

@if (Model.Count==0)
{
    <h6>Bu Departmana Kayıtlı Personel Bulunmamaktadır.</h6>
}

else{
    <table class="table table-bordered">
        <tr>
            <th>Personel ID</th>
            <th>Personel Adı</th>
            <th>Personel Soyadı</th>
            <th>Personel Şehir</th>
        </tr>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.personel_id</td>
                <td>@x.personel_adi</td>
                <td>@x.personel_soyadi</td>
                <td>@x.personel_sehir</td>
            </tr>
        }
    </table>
}

ilk/Views/departman/DepartmanEkle.cshtml
@model ilk.Models.Departman

@{
    ViewData["Title"] = "DepartmanEkle";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />

<br />
<form class="form-group" method="post">
@*    <b>Departman ID</b>
    @Html.TextBoxFor(x => x.departman_id, new { @class = "form-control" })*@
    <br />
    <b>Departman Adı</b>
    @Html.TextBoxFor(x => x.departman_adi, new { @class = "form-control" })

    <br />
    <button class="btn btn-info">Departman Ekle</button>
</form>

ilk/Views/departman/DepartmanGetir.cshtml
@model ilk.Models.Departman
@{
    ViewData["Title"] = "DepartmanGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />

@using (Html.BeginForm("DepartmanGuncelle", "departman", FormMethod.Post))
{
    <b>Departman ID</b>
    @Html.TextBoxFor(x => x.departman_id, new { @class = "form-control", @readonly = "readonly"})
<br />
    <b>Departman Adı</b>
    @Html.TextBoxFor(x => x.departman_adi, new { @class = "form-control" })
    <br />
    <button class="btn btn-default" style="background-color:darkslategrey; color:white;">Departman Güncelle</button>
}

ilk/Views/departman/Index.cshtml
@using ilk.Models

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>Departman ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
   @foreach(var x in Model){
        <tr>
            <td>@x.departman_id</td>
            <td>@x.departman_adi</td>
            <td><a href="/departman/DepartmanSil/@x.departman_id" class="btn btn-danger">Sil</a></td>
            <td><a href="/departman/DepartmanGetir/@x.departman_id" class="btn btn-success">Güncelle</a></td>
            <td><a href="/departman/DepartmanDetay/@x.departman_id" class="btn btn-default" style="background-color:#dee61d">Detaylar</a></td>
        </tr>
    }
</table>

<a href="/departman/DepartmanEkle" class="btn btn-primary">Departman Ekle</a>

ilk/Views/personel/Index.cshtml
@using ilk.Models
@model List<Personel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>Personel ID</th>
        <th>Personel Adı</th>
        <th>Personel Soyadı</th>
        <th>Personel Şehir</th>
        <th>Departman ID</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.personel_id</td>
            <td>@x.personel_adi</td>
            <td>@x.personel_soyadi</td>
            <td>@x.personel_sehir</td>
            <td>@x.Departman.departman_adi</td>
            <td><a href="/personel/PersonelSil/@x.personel_id" class="btn btn-danger">Sil</a></td>
            <td><a href="/personel/PersonelGetir/@x.personel_id" class="btn btn-success">Güncelle</a></td>
            <td><a href="" class="btn btn-default" style="background-color:#dee61d">Detaylar</a></td>
        </tr>
    }
</table>

<a href="/personel/YeniPersonel" class="btn btn-primary">Personel Ekle</a>

ilk/Views/personel/YeniPersonel.cshtml
@model ilk.Models.Personel
@{
    ViewData["Title"] = "YeniPersonel";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />

<br />
<form class="form-group" method="post">
    <br />
    <b>Personel Adı</b>
    @Html.TextBoxFor(x => x.personel_adi, new { @class = "form-control" })
    <br />
    <b>Personel Soyadı</b>
    @Html.TextBoxFor(x => x.personel_soyadi, new { @class = "form-control" })
    <br />
    <b>Personel Şehir</b>
    @Html.TextBoxFor(x => x.personel_sehir, new { @class = "form-control" })
    <br />
    <b>Departman Adı</b>
    @Html.DropDownListFor(x=>x.Departman.departman_id, (IEnumerable<SelectListItem>)ViewBag.dgr, new { @class="form-control"})

    <br />
    <button class="btn btn-info">Personel Ekle</button>
</form>